<!doctype html>
<html lang="ru">
<head>
    <title>Вход</title>
</head>
<body>
<form method="post" action="/login">
    <center><h1>Вход</h1>
        <p><a href="/signUp">Регистрация</a> </p>
        <p>Логин:</p>
        <input type="text" name="username"/>
        <p>Пароль:</p>
        <input type="password" name="password"/>
        <p>
            <input type="submit" id="btn">
        </p></center>
</form>
</body>
</html>