<html>
<head>
    <title>Регистрация</title>
</head>
<body>
<div>
    <form method="post" action="/signUp">
        <center><h1>Регистрация</h1>
        <p><a href="/login">Вход</a> </p>
        <p>Логин:</p>
        <input type="text" name="username"/>
        <p>Пароль:</p>
        <input type="password" name="password"/>
        <p>
            <input type="submit" id="btn">
        </p></center>
    </form>
</div>

</body>
</html>